$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: amlv2_parallel_job
compute: azureml:cpu-cluster

jobs:

  data_engineering:
    type: command
    code: data-engineering
    command: python data-engineering.py --training_data_folder ${{outputs.training_data_folder}}
    outputs:
      training_data_folder:
        type: uri_folder
        path: azureml://datastores/amlv2_pj_training_data/paths/
        mode: rw_mount
    environment: azureml:amlv2-pj-data-engineering@latest

  training:
    type: parallel
    mini_batch_size: "1"
    mini_batch_error_threshold: -1
    input_data: ${{inputs.training_dataset}}
    max_concurrency_per_instance: 2
    retry_settings:
      max_retries: 1
      timeout: 60
    inputs:
      training_dataset:
        type: mltable
        mode: eval_mount
        path: azureml:amlv2_pj_training_data@latest
    outputs:
      training_logs:
        type: uri_folder
        path: azureml://datastores/datalake/paths/amlv2_pj_training_logs/
        mode: rw_mount
    task:
      type: function
      code: training
      entry_script: training.py
      environment: azureml:amlv2-pj-training@latest
      args: --training_data_folder {{parent.jobs.data_engineering.outputs.training_data_folder}}
      append_row_to: ${{outputs.training_logs}}